# Generated by Django 4.0.4 on 2022-05-15 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cashbook',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('mobile_no', models.TextField(blank=True)),
                ('photo', models.TextField(blank=True, default='sample.jpeg')),
                ('email', models.TextField(blank=True)),
                ('password', models.TextField()),
            ],
        ),
    ]
