# Generated by Django 4.0.4 on 2022-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='email',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='photo',
            field=models.CharField(blank=True, default='sample.jpeg', max_length=300),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='username',
            field=models.CharField(max_length=300),
        ),
    ]
