# Generated by Django 4.0.4 on 2022-05-15 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_alter_cashbook_email_alter_cashbook_mobile_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbook',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cashbook',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='cashbook',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cashbook',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cashbook',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='cashbook',
            name='username',
        ),
        migrations.AddField(
            model_name='cashbook',
            name='closing_balance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 10, 20, 4, 884144)),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='opening_balance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='user',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
